# Generated by Django 2.2.12 on 2021-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(default='', max_length=30)),
                ('time', models.DateTimeField(default='')),
                ('details', models.TextField(default='', max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
